💬 Change to Norwegian text and better titles/descs
echo-webkom/sanity-studio pull request #17
Opened 2021-10-25 13:07 UTC by bakseter

jælva nais

![](https://media0.giphy.com/media/azRJjp1WSlQ4ebKMyB/giphy.gif)

2021-10-25 18:59 UTC, bakseter commented on schemas/Happening.js
> +                    { title: 'Nei', value: 'event' },
Skal værra 'EVENT' her

2021-10-25 19:03 UTC, bakseter commented on schemas/SpotRange.js
> +    title: 'Arrangementsplaser',
Plasser, ikke plaser :)

2021-10-25 19:03 UTC, bakseter commented on schemas/StudentGroup.js
> +    title: 'Studengruppe',
Studentgruppe*

2021-10-25 22:01 UTC, boaanes requested changes
Fikse det du selv har kommentert + den jeg kommenterte kanskje

2021-10-25 22:01 UTC, boaanes commented on schemas/JobAdvert.js
> +            title: 'Type stilling',
Stillingstype kanskje?

2021-10-27 13:28 UTC, boaanes approved these changes

2021-10-27 13:28 UTC, merged